# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wesley Tsai
tagline:             Blog
description:         ''
url:                 http://wesleytsai.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Wesley Tsai
  url:               https://github.com/wezleytsai
  email:             &#119;&#101;&#122;&#108;&#101;&#121;&#046;&#116;&#115;&#097;&#105;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;

# Custom vars
mygithub:            https://github.com/wezleytsai
mylinkedin:          https://www.linkedin.com/in/wezleytsai

# Exclude vendor
exclude:             [vendor]

# Sitemap
gems:
  - jekyll-sitemap
