# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wesley Tsai
tagline:             Blog
description:         ''
url:                 http://wesleytsai.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Wesley Tsai
  url:               https://github.com/wezleytsai
  email:             wezley.tsai@gmail.com

# Custom vars
mygithub:            https://github.com/wezleytsai
mylinkedin:          https://www.linkedin.com/in/wezleytsai

# Exclude vendor
exclude:             [vendor]


# TODO: style consecutive posts differently
# TODO: new logo
# TODO: related posts via tags
# TODO: portfolio page
# TODO: profile pic/intro in sidebar
# TODO: blog posts archive/listing
# TODO: post page - change masthead title to post title or something?
